---
- name: Installation and Configuration of k8s cluster
  hosts: all
  become: true
  gather_facts: true

  roles:
    - general
    - {role: master, when: node == "master"}
    - {role: worker, when: node == "worker"}
