---
- name: Installation and Configuration of k8s cluster
  hosts: all
  become: yes
  gather_facts: true

  vars_files:
    - vars/main.yml

  roles:
    - general
    - {role: master, when: node == "master"}
    - {role: worker, when: node == "worker"}
