---
- name: Add DNS alias to each node
  shell: |
    cat >> /etc/hosts <<EOF
    10.18.0.11 cluster-master
    10.18.0.12 cluster-worker1
    10.18.0.13 cluster-worker2
    EOF

- name: Clear memory cache
  shell: sync; echo 3 > /proc/sys/vm/drop_caches
