---
- name: Upload cluster init config file
  template:
    src: templates/cluster-conf.yaml.j2
    dest: "/home/vagrant/cluster-conf.yaml"

- name: Initialize the cluster using kubeadm
  shell: |
    kubeadm init --config=/home/vagrant/cluster-conf.yaml

- name: Setup cluster config on master node
  shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join"

- name: Enable kubectl autocompletion
  shell:
    cmd: kubectl completion bash > /etc/bash_completion.d/kubectl
    # If you do not want to run this when the file already exists, add
    creates: /etc/bash_completion.d/kubectl

- name: Deploy Calico CNI
  become: false
  command: >
    kubectl --kubeconfig /home/vagrant/.kube/config apply -f
    https://docs.projectcalico.org/manifests/calico.yaml
  when: network == "calico"
