---
- name: Upload cluster init config file
  template:
    src: templates/cluster-conf.yaml.j2
    dest: "/home/vagrant/cluster-conf.yaml"

- name: Initialize the cluster using kubeadm
  shell: |
    kubeadm init --config=/home/vagrant/cluster-conf.yaml

- name: Setup cluster config on master node
  shell: |
    mkdir -p /home/vagrant/.kube
    cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    chown vagrant:vagrant /home/vagrant/.kube/config

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join"
  become: false

- name: Deploy Calico to cluster
  command: >
    kubectl --kubeconfig /home/vagrant/.kube/config create -f
    https://docs.projectcalico.org/manifests/calico.yaml
  when: network == "calico"
